name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: checkout

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - run: |
          pip3 install -r requirements.txt